// actions relating to USER
export const CHANGE_USER = 'CHANGE_USERS';
export const CHANGE_CITIES_NUMBER = 'CHANGE_CITIES_NUMBER';

// actions relating to SELECTED
export const UPDATE_CITIES_SELECTED = 'UPDATE_CITIES_SELECTED';
export const UPDATE_TRANSPORT_SELECTED = 'UPDATE_TRANSPORT_SELECTED';
